#ifndef ARDUINO_CONFIG_H
#define ARDUINO_CONFIG_H

#undef DEBUG_STDERR
#undef DEBUG_TFT
#undef DEBUG_SERIAL

#define TFT_DEBUG_DELAY 0
#define STDERR_DEBUG_DELAY 100
#define SERIAL_DEBUG_DELAY 100

#endif /* ARDUINO_CONFIG_H */
